name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd node-app && docker build . --file Dockerfile --tag shahrukhs/eks-demo:$(GITHUB_RUN_NUMBER)
      run: |
        docker login -u shahrukhs -p "${DOCKER_REGISTRY_TOKEN}"
        docker push shahrukhs/eks-demo:$(GITHUB_RUN_NUMBER)
      env:
        DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
