name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd node-app && docker build . --file Dockerfile --tag shahrukhs/eks-demo:$(date +%s)
    - name: Push
      run: |
        docker login --username shahrukhs --password "${DOCKER_REGISTRY_TOKEN}"
        docker push shahrukhs/eks-demo:$(date +%s)
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
